export interface MedicalTerm {
  id: string;
  german: string;
  english: string;
  category: string;
  example?: string;
}

export type TermCategory = 
  | 'Symptome'
  | 'Diagnosen'
  | 'Körperteile'
  | 'Untersuchungen'
  | 'Medikamente'
  | 'Verben'
  | 'Arztbrief'
  | 'Notfall'
  | 'Allgemein';

export const TERM_CATEGORIES: TermCategory[] = [
  'Symptome',
  'Diagnosen',
  'Körperteile',
  'Untersuchungen',
  'Medikamente',
  'Verben',
  'Arztbrief',
  'Notfall',
  'Allgemein',
];

export const MEDICAL_TERMS: MedicalTerm[] = [
  // SYMPTOME (50 terms)
  { id: '1', german: 'die Kopfschmerzen', english: 'headache', category: 'Symptome', example: 'Ich habe starke Kopfschmerzen.' },
  { id: '2', german: 'die Bauchschmerzen', english: 'abdominal pain', category: 'Symptome', example: 'Die Bauchschmerzen sind seit gestern.' },
  { id: '3', german: 'die Übelkeit', english: 'nausea', category: 'Symptome', example: 'Mir ist übel.' },
  { id: '4', german: 'das Erbrechen', english: 'vomiting', category: 'Symptome', example: 'Er hat mehrmals erbrochen.' },
  { id: '5', german: 'der Durchfall', english: 'diarrhea', category: 'Symptome', example: 'Seit wann haben Sie Durchfall?' },
  { id: '6', german: 'die Verstopfung', english: 'constipation', category: 'Symptome', example: 'Sie leidet unter Verstopfung.' },
  { id: '7', german: 'das Fieber', english: 'fever', category: 'Symptome', example: 'Das Fieber ist auf 39 Grad gestiegen.' },
  { id: '8', german: 'der Schwindel', english: 'dizziness', category: 'Symptome', example: 'Mir ist schwindelig.' },
  { id: '9', german: 'die Atemnot', english: 'shortness of breath', category: 'Symptome', example: 'Er klagt über Atemnot.' },
  { id: '10', german: 'der Husten', english: 'cough', category: 'Symptome', example: 'Der Husten ist produktiv.' },
  { id: '11', german: 'der Schnupfen', english: 'runny nose', category: 'Symptome', example: 'Sie hat Schnupfen.' },
  { id: '12', german: 'die Halsschmerzen', english: 'sore throat', category: 'Symptome', example: 'Die Halsschmerzen sind stark.' },
  { id: '13', german: 'die Brustschmerzen', english: 'chest pain', category: 'Symptome', example: 'Er hat Brustschmerzen beim Atmen.' },
  { id: '14', german: 'die Rückenschmerzen', english: 'back pain', category: 'Symptome', example: 'Die Rückenschmerzen strahlen ins Bein aus.' },
  { id: '15', german: 'die Gelenkschmerzen', english: 'joint pain', category: 'Symptome', example: 'Sie hat Gelenkschmerzen in beiden Knien.' },
  { id: '16', german: 'die Müdigkeit', english: 'fatigue', category: 'Symptome', example: 'Die Müdigkeit ist stark ausgeprägt.' },
  { id: '17', german: 'die Schwäche', english: 'weakness', category: 'Symptome', example: 'Er fühlt sich schwach.' },
  { id: '18', german: 'der Ausschlag', english: 'rash', category: 'Symptome', example: 'Der Ausschlag juckt.' },
  { id: '19', german: 'der Juckreiz', english: 'itching', category: 'Symptome', example: 'Der Juckreiz ist unerträglich.' },
  { id: '20', german: 'die Schwellung', english: 'swelling', category: 'Symptome', example: 'Die Schwellung am Knöchel.' },
  { id: '21', german: 'die Blutung', english: 'bleeding', category: 'Symptome', example: 'Die Blutung hat aufgehört.' },
  { id: '22', german: 'der Schmerz', english: 'pain', category: 'Symptome', example: 'Wo genau ist der Schmerz?' },
  { id: '23', german: 'stechend', english: 'stabbing (pain)', category: 'Symptome', example: 'Der Schmerz ist stechend.' },
  { id: '24', german: 'dumpf', english: 'dull (pain)', category: 'Symptome', example: 'Es ist ein dumpfer Schmerz.' },
  { id: '25', german: 'brennend', english: 'burning', category: 'Symptome', example: 'Das Brennen beim Wasserlassen.' },
  { id: '26', german: 'pochend', english: 'throbbing', category: 'Symptome', example: 'Der Schmerz ist pochend.' },
  { id: '27', german: 'krampfartig', english: 'cramping', category: 'Symptome', example: 'Sie hat krampfartige Bauchschmerzen.' },
  { id: '28', german: 'die Taubheit', english: 'numbness', category: 'Symptome', example: 'Die Taubheit in den Fingern.' },
  { id: '29', german: 'das Kribbeln', english: 'tingling', category: 'Symptome', example: 'Ein Kribbeln in den Beinen.' },
  { id: '30', german: 'die Sehstörung', english: 'visual disturbance', category: 'Symptome', example: 'Er hat plötzliche Sehstörungen.' },
  { id: '31', german: 'der Hörverlust', english: 'hearing loss', category: 'Symptome', example: 'Der Hörverlust kam plötzlich.' },
  { id: '32', german: 'der Tinnitus', english: 'tinnitus', category: 'Symptome', example: 'Sie hat einen Tinnitus.' },
  { id: '33', german: 'die Heiserkeit', english: 'hoarseness', category: 'Symptome', example: 'Die Heiserkeit seit einer Woche.' },
  { id: '34', german: 'die Appetitlosigkeit', english: 'loss of appetite', category: 'Symptome', example: 'Er hat keinen Appetit.' },
  { id: '35', german: 'der Gewichtsverlust', english: 'weight loss', category: 'Symptome', example: 'Ein ungewollter Gewichtsverlust.' },
  { id: '36', german: 'die Gewichtszunahme', english: 'weight gain', category: 'Symptome', example: 'Die Gewichtszunahme in letzter Zeit.' },
  { id: '37', german: 'die Schlafstörung', english: 'sleep disorder', category: 'Symptome', example: 'Sie leidet unter Schlafstörungen.' },
  { id: '38', german: 'die Schluckbeschwerden', english: 'difficulty swallowing', category: 'Symptome', example: 'Er hat Schluckbeschwerden.' },
  { id: '39', german: 'das Sodbrennen', english: 'heartburn', category: 'Symptome', example: 'Das Sodbrennen nach dem Essen.' },
  { id: '40', german: 'die Blähungen', english: 'bloating/gas', category: 'Symptome', example: 'Er klagt über Blähungen.' },
  { id: '41', german: 'der Nachtschweiß', english: 'night sweats', category: 'Symptome', example: 'Sie hat starken Nachtschweiß.' },
  { id: '42', german: 'die Kurzatmigkeit', english: 'breathlessness', category: 'Symptome', example: 'Die Kurzatmigkeit bei Belastung.' },
  { id: '43', german: 'das Herzrasen', english: 'palpitations', category: 'Symptome', example: 'Er hat Herzrasen.' },
  { id: '44', german: 'der Schüttelfrost', english: 'chills', category: 'Symptome', example: 'Sie hat Schüttelfrost.' },
  { id: '45', german: 'die Bewusstlosigkeit', english: 'unconsciousness', category: 'Symptome', example: 'Eine kurze Bewusstlosigkeit.' },
  { id: '46', german: 'die Ohnmacht', english: 'fainting', category: 'Symptome', example: 'Er ist in Ohnmacht gefallen.' },
  { id: '47', german: 'der Krampf', english: 'cramp/seizure', category: 'Symptome', example: 'Ein Krampf im Bein.' },
  { id: '48', german: 'die Lähmung', english: 'paralysis', category: 'Symptome', example: 'Eine Lähmung der rechten Seite.' },
  { id: '49', german: 'der Tremor', english: 'tremor', category: 'Symptome', example: 'Ein Tremor in den Händen.' },
  { id: '50', german: 'die Inkontinenz', english: 'incontinence', category: 'Symptome', example: 'Sie hat Harninkontinenz.' },

  // DIAGNOSEN (50 terms)
  { id: '51', german: 'der Bluthochdruck', english: 'hypertension', category: 'Diagnosen', example: 'Der Patient hat Bluthochdruck.' },
  { id: '52', german: 'der Diabetes mellitus', english: 'diabetes mellitus', category: 'Diagnosen', example: 'Diabetes mellitus Typ 2.' },
  { id: '53', german: 'die Herzinsuffizienz', english: 'heart failure', category: 'Diagnosen', example: 'Eine chronische Herzinsuffizienz.' },
  { id: '54', german: 'der Herzinfarkt', english: 'heart attack', category: 'Diagnosen', example: 'Verdacht auf Herzinfarkt.' },
  { id: '55', german: 'der Schlaganfall', english: 'stroke', category: 'Diagnosen', example: 'Zustand nach Schlaganfall.' },
  { id: '56', german: 'die Lungenentzündung', english: 'pneumonia', category: 'Diagnosen', example: 'Eine bakterielle Lungenentzündung.' },
  { id: '57', german: 'die Bronchitis', english: 'bronchitis', category: 'Diagnosen', example: 'Eine akute Bronchitis.' },
  { id: '58', german: 'das Asthma bronchiale', english: 'bronchial asthma', category: 'Diagnosen', example: 'Bekanntes Asthma bronchiale.' },
  { id: '59', german: 'die COPD', english: 'COPD', category: 'Diagnosen', example: 'COPD Stadium III.' },
  { id: '60', german: 'die Gastritis', english: 'gastritis', category: 'Diagnosen', example: 'Eine chronische Gastritis.' },
  { id: '61', german: 'das Magengeschwür', english: 'stomach ulcer', category: 'Diagnosen', example: 'Ein Magengeschwür wurde festgestellt.' },
  { id: '62', german: 'die Appendizitis', english: 'appendicitis', category: 'Diagnosen', example: 'Verdacht auf Appendizitis.' },
  { id: '63', german: 'die Cholezystitis', english: 'cholecystitis', category: 'Diagnosen', example: 'Eine akute Cholezystitis.' },
  { id: '64', german: 'die Hepatitis', english: 'hepatitis', category: 'Diagnosen', example: 'Hepatitis B.' },
  { id: '65', german: 'die Leberzirrhose', english: 'liver cirrhosis', category: 'Diagnosen', example: 'Eine alkoholbedingte Leberzirrhose.' },
  { id: '66', german: 'die Niereninsuffizienz', english: 'renal failure', category: 'Diagnosen', example: 'Chronische Niereninsuffizienz.' },
  { id: '67', german: 'die Harnwegsinfektion', english: 'urinary tract infection', category: 'Diagnosen', example: 'Eine unkomplizierte Harnwegsinfektion.' },
  { id: '68', german: 'die Anämie', english: 'anemia', category: 'Diagnosen', example: 'Eine Eisenmangelanämie.' },
  { id: '69', german: 'die Depression', english: 'depression', category: 'Diagnosen', example: 'Eine mittelgradige Depression.' },
  { id: '70', german: 'die Angststörung', english: 'anxiety disorder', category: 'Diagnosen', example: 'Eine generalisierte Angststörung.' },
  { id: '71', german: 'die Demenz', english: 'dementia', category: 'Diagnosen', example: 'Eine beginnende Demenz.' },
  { id: '72', german: 'die Epilepsie', english: 'epilepsy', category: 'Diagnosen', example: 'Bekannte Epilepsie.' },
  { id: '73', german: 'die Multiple Sklerose', english: 'multiple sclerosis', category: 'Diagnosen', example: 'Multiple Sklerose.' },
  { id: '74', german: 'die Arthrose', english: 'osteoarthritis', category: 'Diagnosen', example: 'Kniearthrose beidseits.' },
  { id: '75', german: 'die Arthritis', english: 'arthritis', category: 'Diagnosen', example: 'Rheumatoide Arthritis.' },
  { id: '76', german: 'die Osteoporose', english: 'osteoporosis', category: 'Diagnosen', example: 'Eine manifeste Osteoporose.' },
  { id: '77', german: 'der Bandscheibenvorfall', english: 'herniated disc', category: 'Diagnosen', example: 'Ein Bandscheibenvorfall L4/L5.' },
  { id: '78', german: 'die Schilddrüsenüberfunktion', english: 'hyperthyroidism', category: 'Diagnosen', example: 'Eine Schilddrüsenüberfunktion.' },
  { id: '79', german: 'die Schilddrüsenunterfunktion', english: 'hypothyroidism', category: 'Diagnosen', example: 'Eine Schilddrüsenunterfunktion.' },
  { id: '80', german: 'die Allergie', english: 'allergy', category: 'Diagnosen', example: 'Allergie gegen Penicillin.' },
  { id: '81', german: 'die Migräne', english: 'migraine', category: 'Diagnosen', example: 'Bekannte Migräne mit Aura.' },
  { id: '82', german: 'das Vorhofflimmern', english: 'atrial fibrillation', category: 'Diagnosen', example: 'Paroxysmales Vorhofflimmern.' },
  { id: '83', german: 'die KHK', english: 'coronary heart disease', category: 'Diagnosen', example: 'Koronare Herzkrankheit.' },
  { id: '84', german: 'die pAVK', english: 'peripheral artery disease', category: 'Diagnosen', example: 'pAVK Stadium IIb.' },
  { id: '85', german: 'die Thrombose', english: 'thrombosis', category: 'Diagnosen', example: 'Tiefe Beinvenenthrombose.' },
  { id: '86', german: 'die Lungenembolie', english: 'pulmonary embolism', category: 'Diagnosen', example: 'Verdacht auf Lungenembolie.' },
  { id: '87', german: 'die Sepsis', english: 'sepsis', category: 'Diagnosen', example: 'Eine beginnende Sepsis.' },
  { id: '88', german: 'die Pneumonie', english: 'pneumonia', category: 'Diagnosen', example: 'Ambulant erworbene Pneumonie.' },
  { id: '89', german: 'die Fraktur', english: 'fracture', category: 'Diagnosen', example: 'Eine distale Radiusfraktur.' },
  { id: '90', german: 'die Prellung', english: 'contusion', category: 'Diagnosen', example: 'Eine Prellung des Knies.' },
  { id: '91', german: 'die Verstauchung', english: 'sprain', category: 'Diagnosen', example: 'Eine Sprunggelenksverstauchung.' },
  { id: '92', german: 'die Gehirnerschütterung', english: 'concussion', category: 'Diagnosen', example: 'Verdacht auf Gehirnerschütterung.' },
  { id: '93', german: 'das Karzinom', english: 'carcinoma', category: 'Diagnosen', example: 'Ein Bronchialkarzinom.' },
  { id: '94', german: 'die Leukämie', english: 'leukemia', category: 'Diagnosen', example: 'Eine akute Leukämie.' },
  { id: '95', german: 'die Gicht', english: 'gout', category: 'Diagnosen', example: 'Ein akuter Gichtanfall.' },
  { id: '96', german: 'die Pankreatitis', english: 'pancreatitis', category: 'Diagnosen', example: 'Eine akute Pankreatitis.' },
  { id: '97', german: 'die Colitis ulcerosa', english: 'ulcerative colitis', category: 'Diagnosen', example: 'Bekannte Colitis ulcerosa.' },
  { id: '98', german: 'der Morbus Crohn', english: 'Crohn\'s disease', category: 'Diagnosen', example: 'Morbus Crohn.' },
  { id: '99', german: 'die Hyperlipidämie', english: 'hyperlipidemia', category: 'Diagnosen', example: 'Eine Hyperlipidämie.' },
  { id: '100', german: 'die Adipositas', english: 'obesity', category: 'Diagnosen', example: 'Adipositas Grad II.' },

  // KÖRPERTEILE (40 terms)
  { id: '101', german: 'der Kopf', english: 'head', category: 'Körperteile' },
  { id: '102', german: 'das Gehirn', english: 'brain', category: 'Körperteile' },
  { id: '103', german: 'das Auge', english: 'eye', category: 'Körperteile' },
  { id: '104', german: 'das Ohr', english: 'ear', category: 'Körperteile' },
  { id: '105', german: 'die Nase', english: 'nose', category: 'Körperteile' },
  { id: '106', german: 'der Mund', english: 'mouth', category: 'Körperteile' },
  { id: '107', german: 'die Zunge', english: 'tongue', category: 'Körperteile' },
  { id: '108', german: 'der Hals', english: 'throat/neck', category: 'Körperteile' },
  { id: '109', german: 'die Schilddrüse', english: 'thyroid', category: 'Körperteile' },
  { id: '110', german: 'die Brust', english: 'chest', category: 'Körperteile' },
  { id: '111', german: 'das Herz', english: 'heart', category: 'Körperteile' },
  { id: '112', german: 'die Lunge', english: 'lung', category: 'Körperteile' },
  { id: '113', german: 'die Leber', english: 'liver', category: 'Körperteile' },
  { id: '114', german: 'die Gallenblase', english: 'gallbladder', category: 'Körperteile' },
  { id: '115', german: 'der Magen', english: 'stomach', category: 'Körperteile' },
  { id: '116', german: 'der Darm', english: 'intestine', category: 'Körperteile' },
  { id: '117', german: 'der Dünndarm', english: 'small intestine', category: 'Körperteile' },
  { id: '118', german: 'der Dickdarm', english: 'large intestine', category: 'Körperteile' },
  { id: '119', german: 'die Bauchspeicheldrüse', english: 'pancreas', category: 'Körperteile' },
  { id: '120', german: 'die Milz', english: 'spleen', category: 'Körperteile' },
  { id: '121', german: 'die Niere', english: 'kidney', category: 'Körperteile' },
  { id: '122', german: 'die Blase', english: 'bladder', category: 'Körperteile' },
  { id: '123', german: 'die Wirbelsäule', english: 'spine', category: 'Körperteile' },
  { id: '124', german: 'das Rückenmark', english: 'spinal cord', category: 'Körperteile' },
  { id: '125', german: 'der Rücken', english: 'back', category: 'Körperteile' },
  { id: '126', german: 'der Bauch', english: 'abdomen', category: 'Körperteile' },
  { id: '127', german: 'die Schulter', english: 'shoulder', category: 'Körperteile' },
  { id: '128', german: 'der Arm', english: 'arm', category: 'Körperteile' },
  { id: '129', german: 'der Ellenbogen', english: 'elbow', category: 'Körperteile' },
  { id: '130', german: 'die Hand', english: 'hand', category: 'Körperteile' },
  { id: '131', german: 'der Finger', english: 'finger', category: 'Körperteile' },
  { id: '132', german: 'das Bein', english: 'leg', category: 'Körperteile' },
  { id: '133', german: 'das Knie', english: 'knee', category: 'Körperteile' },
  { id: '134', german: 'der Fuß', english: 'foot', category: 'Körperteile' },
  { id: '135', german: 'der Knöchel', english: 'ankle', category: 'Körperteile' },
  { id: '136', german: 'die Hüfte', english: 'hip', category: 'Körperteile' },
  { id: '137', german: 'das Gelenk', english: 'joint', category: 'Körperteile' },
  { id: '138', german: 'der Muskel', english: 'muscle', category: 'Körperteile' },
  { id: '139', german: 'der Knochen', english: 'bone', category: 'Körperteile' },
  { id: '140', german: 'die Haut', english: 'skin', category: 'Körperteile' },

  // UNTERSUCHUNGEN (40 terms)
  { id: '141', german: 'die Anamnese', english: 'medical history', category: 'Untersuchungen', example: 'Wir beginnen mit der Anamnese.' },
  { id: '142', german: 'die körperliche Untersuchung', english: 'physical examination', category: 'Untersuchungen', example: 'Ich führe eine körperliche Untersuchung durch.' },
  { id: '143', german: 'die Blutabnahme', english: 'blood draw', category: 'Untersuchungen', example: 'Wir müssen eine Blutabnahme machen.' },
  { id: '144', german: 'das Blutbild', english: 'blood count', category: 'Untersuchungen', example: 'Das Blutbild zeigt eine Anämie.' },
  { id: '145', german: 'die Blutzuckermessung', english: 'blood sugar measurement', category: 'Untersuchungen', example: 'Die Blutzuckermessung war erhöht.' },
  { id: '146', german: 'die Blutdruckmessung', english: 'blood pressure measurement', category: 'Untersuchungen', example: 'Ich messe jetzt den Blutdruck.' },
  { id: '147', german: 'das EKG', english: 'ECG', category: 'Untersuchungen', example: 'Wir machen ein EKG.' },
  { id: '148', german: 'das Röntgen', english: 'X-ray', category: 'Untersuchungen', example: 'Wir brauchen ein Röntgenbild.' },
  { id: '149', german: 'die Sonographie', english: 'ultrasound', category: 'Untersuchungen', example: 'Eine Sonographie des Bauches.' },
  { id: '150', german: 'der Ultraschall', english: 'ultrasound', category: 'Untersuchungen', example: 'Wir machen einen Ultraschall.' },
  { id: '151', german: 'die CT', english: 'CT scan', category: 'Untersuchungen', example: 'Eine CT des Kopfes.' },
  { id: '152', german: 'die MRT', english: 'MRI', category: 'Untersuchungen', example: 'Eine MRT der Wirbelsäule.' },
  { id: '153', german: 'die Endoskopie', english: 'endoscopy', category: 'Untersuchungen', example: 'Eine Magenspiegelung.' },
  { id: '154', german: 'die Gastroskopie', english: 'gastroscopy', category: 'Untersuchungen', example: 'Wir empfehlen eine Gastroskopie.' },
  { id: '155', german: 'die Koloskopie', english: 'colonoscopy', category: 'Untersuchungen', example: 'Eine Darmspiegelung.' },
  { id: '156', german: 'die Biopsie', english: 'biopsy', category: 'Untersuchungen', example: 'Wir entnehmen eine Biopsie.' },
  { id: '157', german: 'die Urinuntersuchung', english: 'urine test', category: 'Untersuchungen', example: 'Wir brauchen eine Urinprobe.' },
  { id: '158', german: 'der Abstrich', english: 'swab', category: 'Untersuchungen', example: 'Wir machen einen Abstrich.' },
  { id: '159', german: 'die Lungenfunktion', english: 'pulmonary function test', category: 'Untersuchungen', example: 'Eine Lungenfunktionsprüfung.' },
  { id: '160', german: 'die Spirometrie', english: 'spirometry', category: 'Untersuchungen', example: 'Wir führen eine Spirometrie durch.' },
  { id: '161', german: 'die Palpation', english: 'palpation', category: 'Untersuchungen', example: 'Ich palpiere den Bauch.' },
  { id: '162', german: 'die Auskultation', english: 'auscultation', category: 'Untersuchungen', example: 'Ich höre die Lunge ab.' },
  { id: '163', german: 'die Perkussion', english: 'percussion', category: 'Untersuchungen', example: 'Ich perkutiere den Thorax.' },
  { id: '164', german: 'die Inspektion', english: 'inspection', category: 'Untersuchungen', example: 'Bei der Inspektion fällt auf...' },
  { id: '165', german: 'der Befund', english: 'finding', category: 'Untersuchungen', example: 'Der Befund ist unauffällig.' },
  { id: '166', german: 'die Vitalzeichen', english: 'vital signs', category: 'Untersuchungen', example: 'Die Vitalzeichen sind stabil.' },
  { id: '167', german: 'die Temperaturmessung', english: 'temperature measurement', category: 'Untersuchungen', example: 'Ich messe die Temperatur.' },
  { id: '168', german: 'die Pulsmessung', english: 'pulse measurement', category: 'Untersuchungen', example: 'Der Puls ist regelmäßig.' },
  { id: '169', german: 'die Laborwerte', english: 'lab values', category: 'Untersuchungen', example: 'Die Laborwerte zeigen...' },
  { id: '170', german: 'die Bildgebung', english: 'imaging', category: 'Untersuchungen', example: 'Wir brauchen eine Bildgebung.' },
  { id: '171', german: 'das Belastungs-EKG', english: 'stress ECG', category: 'Untersuchungen', example: 'Ein Belastungs-EKG.' },
  { id: '172', german: 'die Echokardiographie', english: 'echocardiography', category: 'Untersuchungen', example: 'Eine Herzultraschall.' },
  { id: '173', german: 'die Szintigraphie', english: 'scintigraphy', category: 'Untersuchungen', example: 'Eine Schilddrüsenszintigraphie.' },
  { id: '174', german: 'die Angiographie', english: 'angiography', category: 'Untersuchungen', example: 'Eine Koronarangiographie.' },
  { id: '175', german: 'der Schnelltest', english: 'rapid test', category: 'Untersuchungen', example: 'Ein Corona-Schnelltest.' },
  { id: '176', german: 'die Stuhlprobe', english: 'stool sample', category: 'Untersuchungen', example: 'Wir brauchen eine Stuhlprobe.' },
  { id: '177', german: 'die Punktion', english: 'puncture', category: 'Untersuchungen', example: 'Eine Lumbalpunktion.' },
  { id: '178', german: 'die Allergiediagnostik', english: 'allergy testing', category: 'Untersuchungen', example: 'Wir machen Allergietests.' },
  { id: '179', german: 'der Allergietest', english: 'allergy test', category: 'Untersuchungen', example: 'Ein Pricktest.' },
  { id: '180', german: 'die Tumormarker', english: 'tumor markers', category: 'Untersuchungen', example: 'Wir bestimmen Tumormarker.' },

  // MEDIKAMENTE (40 terms)
  { id: '181', german: 'das Medikament', english: 'medication', category: 'Medikamente', example: 'Welche Medikamente nehmen Sie?' },
  { id: '182', german: 'die Tablette', english: 'tablet', category: 'Medikamente', example: 'Nehmen Sie eine Tablette täglich.' },
  { id: '183', german: 'die Kapsel', english: 'capsule', category: 'Medikamente', example: 'Eine Kapsel morgens.' },
  { id: '184', german: 'die Tropfen', english: 'drops', category: 'Medikamente', example: 'Zehn Tropfen dreimal täglich.' },
  { id: '185', german: 'die Salbe', english: 'ointment', category: 'Medikamente', example: 'Die Salbe dünn auftragen.' },
  { id: '186', german: 'die Creme', english: 'cream', category: 'Medikamente', example: 'Die Creme zweimal täglich.' },
  { id: '187', german: 'das Spray', english: 'spray', category: 'Medikamente', example: 'Das Nasenspray.' },
  { id: '188', german: 'die Spritze', english: 'injection', category: 'Medikamente', example: 'Eine Spritze in den Muskel.' },
  { id: '189', german: 'die Infusion', english: 'infusion', category: 'Medikamente', example: 'Wir geben eine Infusion.' },
  { id: '190', german: 'das Antibiotikum', english: 'antibiotic', category: 'Medikamente', example: 'Ein Antibiotikum für 7 Tage.' },
  { id: '191', german: 'das Schmerzmittel', english: 'painkiller', category: 'Medikamente', example: 'Ein leichtes Schmerzmittel.' },
  { id: '192', german: 'das Fiebermittel', english: 'fever reducer', category: 'Medikamente', example: 'Paracetamol gegen Fieber.' },
  { id: '193', german: 'das Blutdruckmittel', english: 'blood pressure medication', category: 'Medikamente', example: 'Ihr Blutdruckmittel.' },
  { id: '194', german: 'der Blutverdünner', english: 'blood thinner', category: 'Medikamente', example: 'Er nimmt Blutverdünner.' },
  { id: '195', german: 'das Insulin', english: 'insulin', category: 'Medikamente', example: 'Insulin spritzen.' },
  { id: '196', german: 'das Cortison', english: 'cortisone', category: 'Medikamente', example: 'Cortison für kurze Zeit.' },
  { id: '197', german: 'das Antihistaminikum', english: 'antihistamine', category: 'Medikamente', example: 'Ein Antihistaminikum bei Allergie.' },
  { id: '198', german: 'das Antidepressivum', english: 'antidepressant', category: 'Medikamente', example: 'Ein Antidepressivum.' },
  { id: '199', german: 'das Beruhigungsmittel', english: 'sedative', category: 'Medikamente', example: 'Ein leichtes Beruhigungsmittel.' },
  { id: '200', german: 'das Schlafmittel', english: 'sleeping pill', category: 'Medikamente', example: 'Kein Schlafmittel.' },
  { id: '201', german: 'die Nebenwirkung', english: 'side effect', category: 'Medikamente', example: 'Mögliche Nebenwirkungen.' },
  { id: '202', german: 'die Dosierung', english: 'dosage', category: 'Medikamente', example: 'Die richtige Dosierung.' },
  { id: '203', german: 'die Wechselwirkung', english: 'interaction', category: 'Medikamente', example: 'Gibt es Wechselwirkungen?' },
  { id: '204', german: 'das Rezept', english: 'prescription', category: 'Medikamente', example: 'Ich schreibe ein Rezept.' },
  { id: '205', german: 'rezeptpflichtig', english: 'prescription-only', category: 'Medikamente', example: 'Das ist rezeptpflichtig.' },
  { id: '206', german: 'rezeptfrei', english: 'over-the-counter', category: 'Medikamente', example: 'Das bekommen Sie rezeptfrei.' },
  { id: '207', german: 'nüchtern', english: 'on empty stomach', category: 'Medikamente', example: 'Nüchtern einnehmen.' },
  { id: '208', german: 'das Diuretikum', english: 'diuretic', category: 'Medikamente', example: 'Ein wassertreibendes Mittel.' },
  { id: '209', german: 'der Betablocker', english: 'beta blocker', category: 'Medikamente', example: 'Ein Betablocker.' },
  { id: '210', german: 'der ACE-Hemmer', english: 'ACE inhibitor', category: 'Medikamente', example: 'Ein ACE-Hemmer.' },
  { id: '211', german: 'das Statin', english: 'statin', category: 'Medikamente', example: 'Ein Cholesterinsenker.' },
  { id: '212', german: 'das PPI', english: 'PPI', category: 'Medikamente', example: 'Ein Magenschutz.' },
  { id: '213', german: 'der Magenschutz', english: 'stomach protection', category: 'Medikamente', example: 'Mit Magenschutz.' },
  { id: '214', german: 'das Asthmaspray', english: 'asthma inhaler', category: 'Medikamente', example: 'Das Notfallspray.' },
  { id: '215', german: 'das Nasenspray', english: 'nasal spray', category: 'Medikamente', example: 'Abschwellendes Nasenspray.' },
  { id: '216', german: 'das Augentropfen', english: 'eye drops', category: 'Medikamente', example: 'Augentropfen dreimal täglich.' },
  { id: '217', german: 'das Zäpfchen', english: 'suppository', category: 'Medikamente', example: 'Ein Fieberzäpfchen.' },
  { id: '218', german: 'das Pflaster', english: 'patch/bandage', category: 'Medikamente', example: 'Ein Schmerzpflaster.' },
  { id: '219', german: 'die Impfung', english: 'vaccination', category: 'Medikamente', example: 'Eine Grippeimpfung.' },
  { id: '220', german: 'der Impfstoff', english: 'vaccine', category: 'Medikamente', example: 'Der Corona-Impfstoff.' },

  // VERBEN (40 terms)
  { id: '221', german: 'untersuchen', english: 'to examine', category: 'Verben', example: 'Ich werde Sie untersuchen.' },
  { id: '222', german: 'abtasten', english: 'to palpate', category: 'Verben', example: 'Ich taste den Bauch ab.' },
  { id: '223', german: 'abhören', english: 'to auscultate', category: 'Verben', example: 'Ich höre die Lunge ab.' },
  { id: '224', german: 'messen', english: 'to measure', category: 'Verben', example: 'Ich messe den Blutdruck.' },
  { id: '225', german: 'verschreiben', english: 'to prescribe', category: 'Verben', example: 'Ich verschreibe Ihnen...' },
  { id: '226', german: 'einnehmen', english: 'to take (medicine)', category: 'Verben', example: 'Nehmen Sie das Medikament ein.' },
  { id: '227', german: 'ausstrahlen', english: 'to radiate', category: 'Verben', example: 'Der Schmerz strahlt aus.' },
  { id: '228', german: 'überweisen', english: 'to refer', category: 'Verben', example: 'Ich überweise Sie zum Spezialisten.' },
  { id: '229', german: 'aufnehmen', english: 'to admit', category: 'Verben', example: 'Wir nehmen Sie auf.' },
  { id: '230', german: 'entlassen', english: 'to discharge', category: 'Verben', example: 'Sie können entlassen werden.' },
  { id: '231', german: 'operieren', english: 'to operate', category: 'Verben', example: 'Wir müssen operieren.' },
  { id: '232', german: 'nähen', english: 'to suture', category: 'Verben', example: 'Die Wunde wird genäht.' },
  { id: '233', german: 'verbinden', english: 'to bandage', category: 'Verben', example: 'Ich verbinde die Wunde.' },
  { id: '234', german: 'röntgen', english: 'to X-ray', category: 'Verben', example: 'Wir müssen röntgen.' },
  { id: '235', german: 'spritzen', english: 'to inject', category: 'Verben', example: 'Ich spritze ein Schmerzmittel.' },
  { id: '236', german: 'punktieren', english: 'to puncture', category: 'Verben', example: 'Wir punktieren das Gelenk.' },
  { id: '237', german: 'diagnostizieren', english: 'to diagnose', category: 'Verben', example: 'Wir haben diagnostiziert...' },
  { id: '238', german: 'behandeln', english: 'to treat', category: 'Verben', example: 'Wir behandeln die Infektion.' },
  { id: '239', german: 'heilen', english: 'to heal', category: 'Verben', example: 'Die Wunde heilt gut.' },
  { id: '240', german: 'lindern', english: 'to relieve', category: 'Verben', example: 'Das lindert die Schmerzen.' },
  { id: '241', german: 'betäuben', english: 'to anesthetize', category: 'Verben', example: 'Wir betäuben lokal.' },
  { id: '242', german: 'desinfizieren', english: 'to disinfect', category: 'Verben', example: 'Ich desinfiziere die Stelle.' },
  { id: '243', german: 'abnehmen (Blut)', english: 'to draw (blood)', category: 'Verben', example: 'Ich nehme Blut ab.' },
  { id: '244', german: 'schlucken', english: 'to swallow', category: 'Verben', example: 'Können Sie schlucken?' },
  { id: '245', german: 'atmen', english: 'to breathe', category: 'Verben', example: 'Atmen Sie tief ein.' },
  { id: '246', german: 'husten', english: 'to cough', category: 'Verben', example: 'Husten Sie mal.' },
  { id: '247', german: 'sich übergeben', english: 'to vomit', category: 'Verben', example: 'Haben Sie sich übergeben?' },
  { id: '248', german: 'bluten', english: 'to bleed', category: 'Verben', example: 'Die Wunde blutet.' },
  { id: '249', german: 'anschwellen', english: 'to swell', category: 'Verben', example: 'Der Knöchel ist angeschwollen.' },
  { id: '250', german: 'jucken', english: 'to itch', category: 'Verben', example: 'Es juckt sehr.' },
  { id: '251', german: 'brennen', english: 'to burn', category: 'Verben', example: 'Es brennt beim Wasserlassen.' },
  { id: '252', german: 'stechen', english: 'to sting/stab', category: 'Verben', example: 'Es sticht hier.' },
  { id: '253', german: 'ziehen', english: 'to pull', category: 'Verben', example: 'Ein ziehendes Gefühl.' },
  { id: '254', german: 'drücken', english: 'to press', category: 'Verben', example: 'Tut es weh, wenn ich drücke?' },
  { id: '255', german: 'sich erholen', english: 'to recover', category: 'Verben', example: 'Sie erholen sich gut.' },
  { id: '256', german: 'sich verschlechtern', english: 'to worsen', category: 'Verben', example: 'Hat es sich verschlechtert?' },
  { id: '257', german: 'sich verbessern', english: 'to improve', category: 'Verben', example: 'Es hat sich verbessert.' },
  { id: '258', german: 'kontrollieren', english: 'to check/monitor', category: 'Verben', example: 'Wir kontrollieren regelmäßig.' },
  { id: '259', german: 'dokumentieren', english: 'to document', category: 'Verben', example: 'Ich dokumentiere alles.' },
  { id: '260', german: 'aufklären', english: 'to inform/explain', category: 'Verben', example: 'Ich kläre Sie auf.' },

  // ARZTBRIEF (25 terms)
  { id: '261', german: 'der Arztbrief', english: 'medical report', category: 'Arztbrief', example: 'Der Arztbrief wird erstellt.' },
  { id: '262', german: 'die Epikrise', english: 'epicrisis/discharge summary', category: 'Arztbrief', example: 'Die Epikrise fasst zusammen...' },
  { id: '263', german: 'die Aufnahmediagnose', english: 'admission diagnosis', category: 'Arztbrief', example: 'Die Aufnahmediagnose lautet...' },
  { id: '264', german: 'die Entlassdiagnose', english: 'discharge diagnosis', category: 'Arztbrief', example: 'Die Entlassdiagnose.' },
  { id: '265', german: 'die Hauptdiagnose', english: 'main diagnosis', category: 'Arztbrief', example: 'Die Hauptdiagnose ist...' },
  { id: '266', german: 'die Nebendiagnose', english: 'secondary diagnosis', category: 'Arztbrief', example: 'Als Nebendiagnose besteht...' },
  { id: '267', german: 'die Verdachtsdiagnose', english: 'suspected diagnosis', category: 'Arztbrief', example: 'Die Verdachtsdiagnose.' },
  { id: '268', german: 'die Differentialdiagnose', english: 'differential diagnosis', category: 'Arztbrief', example: 'Differentialdiagnostisch...' },
  { id: '269', german: 'der Aufnahmegrund', english: 'reason for admission', category: 'Arztbrief', example: 'Der Aufnahmegrund war...' },
  { id: '270', german: 'die Eigenanamnese', english: 'personal history', category: 'Arztbrief', example: 'In der Eigenanamnese...' },
  { id: '271', german: 'die Familienanamnese', english: 'family history', category: 'Arztbrief', example: 'Die Familienanamnese zeigt...' },
  { id: '272', german: 'die Sozialanamnese', english: 'social history', category: 'Arztbrief', example: 'Sozialanamnestisch...' },
  { id: '273', german: 'der Verlauf', english: 'course', category: 'Arztbrief', example: 'Der stationäre Verlauf.' },
  { id: '274', german: 'die Therapie', english: 'therapy', category: 'Arztbrief', example: 'Die eingeleitete Therapie.' },
  { id: '275', german: 'die Procedere', english: 'procedure/plan', category: 'Arztbrief', example: 'Das weitere Procedere.' },
  { id: '276', german: 'die Empfehlung', english: 'recommendation', category: 'Arztbrief', example: 'Unsere Empfehlungen.' },
  { id: '277', german: 'die Medikation', english: 'medication list', category: 'Arztbrief', example: 'Die aktuelle Medikation.' },
  { id: '278', german: 'die Entlassmedikation', english: 'discharge medication', category: 'Arztbrief', example: 'Die Entlassmedikation.' },
  { id: '279', german: 'die Wiedervorstellung', english: 'follow-up', category: 'Arztbrief', example: 'Wiedervorstellung in 2 Wochen.' },
  { id: '280', german: 'die Kontrolle', english: 'check-up', category: 'Arztbrief', example: 'Kontrolle beim Hausarzt.' },
  { id: '281', german: 'die Rehabilitation', english: 'rehabilitation', category: 'Arztbrief', example: 'Eine Anschlussheilbehandlung.' },
  { id: '282', german: 'die AHB', english: 'follow-up rehab', category: 'Arztbrief', example: 'Eine AHB wurde beantragt.' },
  { id: '283', german: 'die Prognose', english: 'prognosis', category: 'Arztbrief', example: 'Die Prognose ist günstig.' },
  { id: '284', german: 'die Arbeitsunfähigkeit', english: 'inability to work', category: 'Arztbrief', example: 'Arbeitsunfähig für 2 Wochen.' },
  { id: '285', german: 'die AU-Bescheinigung', english: 'sick note', category: 'Arztbrief', example: 'Eine AU-Bescheinigung.' },

  // NOTFALL (15 terms)
  { id: '286', german: 'der Notfall', english: 'emergency', category: 'Notfall', example: 'Das ist ein Notfall!' },
  { id: '287', german: 'die Notaufnahme', english: 'emergency room', category: 'Notfall', example: 'In die Notaufnahme.' },
  { id: '288', german: 'die Reanimation', english: 'resuscitation', category: 'Notfall', example: 'Eine Reanimation.' },
  { id: '289', german: 'der Kreislaufstillstand', english: 'cardiac arrest', category: 'Notfall', example: 'Ein Kreislaufstillstand.' },
  { id: '290', german: 'der Schock', english: 'shock', category: 'Notfall', example: 'Der Patient ist im Schock.' },
  { id: '291', german: 'die Intubation', english: 'intubation', category: 'Notfall', example: 'Eine Notfallintubation.' },
  { id: '292', german: 'die Beatmung', english: 'ventilation', category: 'Notfall', example: 'Maschinelle Beatmung.' },
  { id: '293', german: 'der Rettungsdienst', english: 'emergency services', category: 'Notfall', example: 'Der Rettungsdienst kommt.' },
  { id: '294', german: 'der Krankenwagen', english: 'ambulance', category: 'Notfall', example: 'Rufen Sie den Krankenwagen!' },
  { id: '295', german: 'die Triage', english: 'triage', category: 'Notfall', example: 'Die Triage erfolgt.' },
  { id: '296', german: 'die Intensivstation', english: 'intensive care unit', category: 'Notfall', example: 'Verlegung auf die Intensivstation.' },
  { id: '297', german: 'der Defibrillator', english: 'defibrillator', category: 'Notfall', example: 'Den Defibrillator holen!' },
  { id: '298', german: 'die Thoraxdrainage', english: 'chest tube', category: 'Notfall', example: 'Eine Thoraxdrainage legen.' },
  { id: '299', german: 'die Bluttransfusion', english: 'blood transfusion', category: 'Notfall', example: 'Eine Bluttransfusion.' },
  { id: '300', german: 'die Stabilisierung', english: 'stabilization', category: 'Notfall', example: 'Erst die Stabilisierung.' },
];

export function getTermsByCategory(category: TermCategory): MedicalTerm[] {
  return MEDICAL_TERMS.filter(term => term.category === category);
}

export function searchTerms(query: string): MedicalTerm[] {
  const lowerQuery = query.toLowerCase();
  return MEDICAL_TERMS.filter(
    term =>
      term.german.toLowerCase().includes(lowerQuery) ||
      term.english.toLowerCase().includes(lowerQuery)
  );
}

export function getRandomTerms(count: number): MedicalTerm[] {
  const shuffled = [...MEDICAL_TERMS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
